name: Flask Application CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
            pip install -r requirements

      - name: Run Tests
        run: |
          python tests.py

      - name: Run Flask Application
        run: |
          export FLASK_APP=microblog.py
          export FLASK_ENV=development
          flask run
